// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzvnplhdoeuqwlexiuit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6dm5wbGhkb2V1cXdsZXhpdWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDA5MzUsImV4cCI6MjA3MTE3NjkzNX0.gmOmJF1W-DTQQQZE7e5nEAiiZcvzbVo40zx7qSGA38U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});